language: node_js
node_js:
  - '4'

env:
  global:
  - ENCRYPTION_LABEL: "02f48b5e2393"
  - COMMIT_AUTHOR_EMAIL: "patternfly-build@redhat.com"

cache:
  directories:
    - node_modules

script:
  - npm run gulp patternlab:build

after_success:
  - ./scripts/publish.sh
