language: node_js
node_js:
  - '4'

env:
  - CXX=g++-4.8
  global:
  - ENCRYPTION_LABEL: "02f48b5e2393"
  - COMMIT_AUTHOR_EMAIL: "patternfly-build@redhat.com"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

cache:
  directories:
    - node_modules

script:
  - npm run gulp patternlab:build

after_success:
  - ./scripts/publish.sh
